### ISSUE TITLE
/etc/newrelic/newrelic_haproxy_agent.yml doesn't exist after install

### ISSUE THREAD

**Issue by Dmitry1987** [railsware/newrelic_platform_plugins#53]
Hello, I've installed using steps from readme, on centos 6:

yum install ruby, rubygems, gcc, ruby-devel -y
gem install newrelic_haproxy_agent

tried to to open  "/etc/newrelic/newrelic_haproxy_agent.yml "  but there's no such file.

EDIT:  then i saw it's my fault and i missed a step  "sudo newrelic_haproxy_agent install".
but running this command says some ruby errors, missing libraries?  how do i know what else to install, is there a list of needed libraries or something?

Thank you.

P.S. here's the error:
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- bundler/setup (LoadError)
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
        from /usr/lib/ruby/gems/1.8/gems/newrelic_haproxy_agent-1.0.1/lib/newrelic_haproxy_agent.rb:4
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
        from /usr/lib/ruby/gems/1.8/gems/newrelic_haproxy_agent-1.0.1/bin/newrelic_haproxy_agent:5
        from /usr/bin/newrelic_haproxy_agent:19:in `load'
        from /usr/bin/newrelic_haproxy_agent:19

EDIT: it's ok figured out,  
gem install bundler
gem install fastercsv

then worked. 
Thanks.

**Comment by Dmitry1987** [comment]
Guys that find this topic from google, do this on centos 6 if you encounter same error:

yum install ruby, rubygems, gcc, ruby-devel -y
gem install bundler
gem install fastercsv
gem install newrelic_haproxy_agent

for installation to succeed.
